min_version = "2026.7.6"

[bootstrap.mise_shell_activate]
bashrc = {enabled = true, mode = "activate"}
bash_profile = {enabled = true, mode = "shims"}

[dotfiles]
# Link this repo's mise.toml to ~/.config.mise/config.toml
"~/.config/mise/config.toml" = "mise.toml"

# Override default mise install/cache directories
"~/.bashrc/mise-storage" = { block = '''
export MISE_STORAGE_OVERRIDE_DIR=/build/${USER}
export MISE_DATA_DIR="${MISE_STORAGE_OVERRIDE_DIR}/mise-${USER}/data"
export MISE_CACHE_DIR="${MISE_STORAGE_OVERRIDE_DIR}/mise-${USER}/cache"
''' }

# Helper to open ghq repo in vscode
"~/.bashrc/qcode" = { block = '''
qcode() {
  local parent_mode=false
  local query=""

  # Check if the first argument is the parent flag
  if [ "$1" = "-p" ]; then
    parent_mode=true
    query="$2"
  else
    query="$1"
  fi

  local repo
  repo=$(ghq list --full-path | fzf --exact --query="$query" --select-1 --exit-0)

  if [ -n "$repo" ]; then
    if [ "$parent_mode" = true ]; then
      # Extracts the parent directory (e.g., handles the owner/org folder)
      local parent_dir
      parent_dir=$(dirname "$repo")
      code "$parent_dir"
    else
      code "$repo"
    fi
  fi
}
''' }

[env]
# Forces the sync utility to use the standard Linux bash-completion user directory
MISE_COMPLETIONS_SYNC_BASH_DIR = "{{env.HOME}}/.local/share/bash-completion/completions"

# Set root dir for ghq-cloned repos
GHQ_ROOT = "{{env.HOME}}/repos"

[tasks.upgrade]
description = "Upgrades mise + tools, prunes old versions"
run = [
  "mise self-update",
  "mise upgrade --bump",
  "mise prune"
]

[hooks]
# Install/setup completions
postinstall = [
  "mise completion bash --include-bash-completion-lib > ${MISE_COMPLETIONS_SYNC_BASH_DIR}/mise",
  "misecompsync --shell bash",
]

[tools]
# Required for cargo: types
"core:rust" = "1.97.0"

# Magic completions?
"cargo:mise-completions-sync" = "0.5.10"
"aqua:jdx/usage" = "latest"

# For just and just accessories
"aqua:casey/just" = "1.56.0"
"cargo:just-lsp" = "0.4.8"

# For Todo Tree extension and other ripgrep purposes
"aqua:BurntSushi/ripgrep" = "15.2.0"

# For python
"aqua:astral-sh/uv" = "0.11.29"

# For GitLab stuff
"gitlab:gitlab-org/cli" = "1.108.0"

# For commit hooks
# TODO: This adds two binaries: lefthook, lefthook_2.1.10_Linux_x86_64
"aqua:evilmartians/lefthook" = "2.1.10"

# For container stuff
"aqua:hadolint/hadolint" = "2.14.0"

# Structured git repo cloning
"aqua:x-motemen/ghq" = "1.10.1"

# Fuzzy finding
"aqua:junegunn/fzf" = "0.74.0"
